// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4RFl6TbsYKiAoGMBPFl_iTfAAUrdFbHo',
    appId: '1:546568219559:android:439d62790e98c4b040e482',
    messagingSenderId: '546568219559',
    projectId: 'binokids-679db',
    databaseURL: 'https://binokids-679db.firebaseio.com',
    storageBucket: 'binokids-679db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBcvQ5I-sPVAGsksMLi8qHWzsOdZ7-mZk',
    appId: '1:546568219559:ios:53221811fab0de1440e482',
    messagingSenderId: '546568219559',
    projectId: 'binokids-679db',
    databaseURL: 'https://binokids-679db.firebaseio.com',
    storageBucket: 'binokids-679db.appspot.com',
    iosClientId: '546568219559-t3b88q9snv5aqok82phvrstdq55q8sr7.apps.googleusercontent.com',
    iosBundleId: 'org.reactjs.native.BinoKids',
  );
}
