class AppRoutes{
  static const String HOME_SCREEN_ROUTE='HOME_SCREEN_ROUTE';
  static const String LOGIN_SCREEN_ROUTE='LOGIN_SCREEN_ROUTE';
  static const String USER_MESSAGES_SCREEN_ROUTE='USER_MESSAGES_SCREEN_ROUTE';
  static const String PRODUCTS_WITH_FILTER_SCREEN_ROUTE='PRODUCTS_WITH_FILTER_SCREEN_ROUTE';
  static const String PRUDUCT_DETAILS_SCREEN_ORUTE="PRUDUCT_DETAILS_SCREEN_ORUTE";
  static const String CART_ITEMS_SCREEN_ROUTE="CART_ITEMS_SCREEN_ROUTE";
  static const String ABOUT_US_SCREEN_ROUTE="ABOUT_US_SCREEN_ROUTE";
  static const String PRIVACY_POLICY_SCREEN_ROUTE="PRIVACY_POLICY_SCREEN_ROUTE";
  static const String RETURN_POLICY_SCREEN_ROUTE="RETURN_POLICY_SCREEN_ROUTE";
  static const String SHIPPING_POLICY_SCREEN_ROUTE="SHIPPING_POLICY_SCREEN_ROUTE";

  static const String ALL_ORDERS_SCREEN_ROUTE="ALL_ORDERS_SCREEN_ROUTE";
  static const String SETTINGS_SCREEN_ROUTE="SETTINGS_SCREEN_ROUTE";
  static const String SEARCH_SCREEN_ROUTE="SEARCH_SCREEN_ROUTE";









}