class AppRoutes{
  static const String HOME_SCREEN_ROUTE='HOME_SCREEN_ROUTE';
  static const String LOGIN_SCREEN_ROUTE='LOGIN_SCREEN_ROUTE';
  static const String USER_MESSAGES_SCREEN_ROUTE='USER_MESSAGES_SCREEN_ROUTE';
  static const String PRODUCTS_WITH_FILTER_SCREEN_ROUTE='PRODUCTS_WITH_FILTER_SCREEN_ROUTE';
  static const String PRUDUCT_DETAILS_SCREEN_ORUTE="PRUDUCT_DETAILS_SCREEN_ORUTE";
  static const String CART_ITEMS_SCREEN_ROUTE="CART_ITEMS_SCREEN_ROUTE";
  static const String ABOUT_US_SCREEN_ROUTE="ABOUT_US_SCREEN_ROUTE";
  static const String PRIVACY_POLICY_SCREEN_ROUTE="PRIVACY_POLICY_SCREEN_ROUTE";
  static const String RETURN_POLICY_SCREEN_ROUTE="RETURN_POLICY_SCREEN_ROUTE";
  static const String SHIPPING_POLICY_SCREEN_ROUTE="SHIPPING_POLICY_SCREEN_ROUTE";

  static const String ALL_ORDERS_SCREEN_ROUTE="ALL_ORDERS_SCREEN_ROUTE";
  static const String ORDER_DETAILS_SCREEN_ROUTE="ORDER_DETAILS_SCREEN_ROUTE";

  static const String SETTINGS_SCREEN_ROUTE="SETTINGS_SCREEN_ROUTE";
  static const String SEARCH_SCREEN_ROUTE="SEARCH_SCREEN_ROUTE";
  static const String REGISTER_SCREEN_ROUTE="REGISTER_SCREEN_ROUTE";
  static const String IMAGES_SCREEN_ROUTE="IMAGES_SCREEN_ROUTE";
  static const String PAYMENT_SCREEN_ROUT="PAYMENT_SCREEN_ROUT";
  static const String OTP_SCREEN_ROUT="OTP_SCREEN_ROUT";
  static const String BRANCHES_SCREEN_ROUT="BRANCHES_SCREEN_ROUT";
  static const String COMPLETE_ORDER_SCREEN_ROUT="COMPLETE_ORDER_SCREEN_ROUT";
  static const String SEE_ALL_SCREENN_ROUT="SEE_ALL_SCREENN_ROUT";
  static const String NO_INTERNET_ROUT="NO_INTERNET_ROUT";
  static const String FORGET_PASSWORD_SCREEN_ROUT="FORGET_PASSWORD_SCREEN_ROUT";
  static const String CHANGE_PASSWORD_SCREEN_ROUT="CHANGE_PASSWORD_SCREEN_ROUT";

















}