class AppRoutes{
  static const String HOME_SCREEN_ROUTE='HOME_SCREEN_ROUTE';
  static const String LOGIN_SCREEN_ROUTE='LOGIN_SCREEN_ROUTE';
  static const String USER_MESSAGES_SCREEN_ROUTE='USER_MESSAGES_SCREEN_ROUTE';
  static const String PRODUCTS_WITH_FILTER_SCREEN_ROUTE='PRODUCTS_WITH_FILTER_SCREEN_ROUTE';
  static const String PRUDUCT_DETAILS_SCREEN_ORUTE="PRUDUCT_DETAILS_SCREEN_ORUTE";
  static const String CART_ITEMS_SCREEN_ROUTE="CART_ITEMS_SCREEN_ROUTE";




}